### ISSUE TITLE
Could not load /userdata/roms/pico8/console.p8

### ISSUE THREAD

**Issue by galactical1100** [Pixelpunker/Pico-Host#1]
I've just installed PICO-8 to the GPM280 following the instructions at https://www.lexaloffle.com/bbs/?tid=41308 and I was able to load into PICO-8 after a successful installation, but after starting PICO-8 I'm given this message and unable to access Splore, or any other part of the console as I do not have a keyboard for the device. :Could not load /userdata/roms/pico8/console.p8"

**Comment by Pixelpunker** [comment]
I have updated some files in pico-host.zip. Repeat the steps from Chapter "Finish Setup" on to update your install. This will also add api.p8 where you can test the (swapped) controls
